[package]
name = "oxidiz_econf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
glob = "0.3.1"
log = "0.4.20"